fix: ramen test should wait worker stats
rixed/ramen pull request #1255
Opened 2020-09-11 14:39 UTC by darlentar

fix #1254

2020-09-13 15:46 UTC, rixed requested changes

2020-09-13 15:46 UTC, rixed commented on src/RamenTests.ml
> +    while !null_stats_i; do
I think I get the idea, but there are several problems with this implementation:

- First and foremost, indentation is bogus :)
- Second, the style is needlessly imperative
- Then, this is busy looping!
- Finally, I'm not convinced that a separate thread is needed here. Why not wait for the stat reports in the main current thread?

2020-09-13 15:46 UTC, rixed commented on src/RamenTests.ml
> +  let test_is_not_finished = ref true in
Let's avoid double negations

2020-09-13 15:46 UTC, rixed commented on src/RamenTests.ml
> -  join_thread "supervisor" supervisor_thread ;
Why not?

2020-09-14 08:06 UTC, darlentar commented on src/RamenTests.ml
> -  join_thread "supervisor" supervisor_thread ;
? I wait the thread when I want to terminate the supervisor just a few lines above.

2020-09-14 08:20 UTC, darlentar commented on src/RamenTests.ml
> +    while !null_stats_i; do
First -> Ok.
Second -> Yes, it is really a problem ? Would you prefer a rec loop ?
Third -> Right. I could add a sleepf(500) WDYT? 
Fourth -> ? I need to read the values with `process_until` in the same time so I need a thread.

2020-09-22 19:35 UTC, rixed commented on src/RamenTests.ml
> +    while !null_stats_i; do
Process_until is just a loop calling process_in until some condition is met.
Your condition is that we have fresh stats for all workers.
Can't you just do: `process_until "stats_are_received" ~while_ session all_stats_are_fresh` with `all_stats_are_fresh : unit -> bool` returning true if every stat report's stats_time is after `now` (or some timeout) ?

2020-09-22 19:37 UTC, rixed commented on src/RamenTests.ml
> -  join_thread "supervisor" supervisor_thread ;
true

2020-09-22 19:39 UTC, rixed commented on src/CodeGenLib_Skeletons.ml
>        exit (!quit |? ExitCodes.terminated)
Wouldn't that make sense to have this fix in a distinct commit?

2020-09-22 19:42 UTC, rixed commented on src/RamenSupervisor.ml
> +  in
What's wrong with `RamenHelpers.waitall_once` ?

2020-09-22 19:44 UTC, rixed commented on src/RamenSupervisor.ml
> +let synchronize_running ?(while_=fun () -> !Processes.quit = None)
Let's not make a special case: use `always` as the default value for while_.

2020-09-22 19:47 UTC, rixed commented on src/RamenTests.ml
> +  let ok, max_retries_tested, stats =
Once you have that `all_stats_are_fresh` function you can do away with this inelegant `max_retries_tested`.

2020-09-23 08:21 UTC, darlentar commented on src/RamenTests.ml
> +    while !null_stats_i; do
We can't currently do this with the current implementation of `process_until` as we need a way to update the stats state. 
Currently code of `process_until` (well it's `process_in` actually) is:
```
      | msg ->
          Client.process_msg session.clt msg ;
          if not single then loop ()
```
We do not do anything but reading incoming messages from the server. A solution could be to add a `process ` parameter and do something like
```diff
       | msg ->
           Client.process_msg session.clt msg ;
+          process msg ;
           if not single then loop ()
```

WDYT ?

2020-09-23 08:28 UTC, darlentar commented on src/RamenSupervisor.ml
> +  in
I just don't see these function but indeed it works.

2020-09-23 08:35 UTC, darlentar commented on src/CodeGenLib_Skeletons.ml
>        exit (!quit |? ExitCodes.terminated)
I don't know if you want too. I put the fix in this commit as the bug is revealed by the fact I'm waiting the stats. I can do another commit though.

2020-09-23 09:05 UTC, darlentar commented on src/RamenTests.ml
> +    while !null_stats_i; do
Oh i see. I will do this !

2020-09-30 19:36 UTC, rixed commented
Your new approach is too sophisticated for this fix.

Once the workers do publish their stats before quitting (there was yet another fix required for that), the solution is rather simple: just terminate confserver last, after all received stats have a timestamp greater than the end of the tests (not really required in practice, just to be extra secure).
That's quite similar to your original approach, with no additional thread needed.

I've done this in master and checked that it worked, therefore closing.

2020-09-30 19:36 UTC, closed without merging